/*
PROBLEM: Happy Number
DESCRIPTION: Write an algorithm to determine if a number n is "happy". A happy number is
defined by the following process: starting with any positive integer, replace the number by
the sum of the squares of its digits; repeat the process until the number equals 1 (where it
will stay), or it loops endlessly in a cycle that does not include 1. Return true if n is
happy, and false if not.
CONSTRAINTS:
- 1 <= n <= 2^31 - 1
EXAMPLE INPUT/OUTPUT:
- Input: n = 19
  Output: true  (19 -> 1^2+9^2=82 -> 8^2+2^2=68 -> 6^2+8^2=100 -> 1^2+0^2+0^2=1)
- Input: n = 2
  Output: false  (2 -> 4 -> 16 -> 37 -> 58 -> 89 -> 145 -> 42 -> 20 -> 4 -> ... loops forever)
*/

/*
APPROACH:
The sequence generated by repeatedly summing squared digits either reaches 1 (happy) or
enters a cycle that never includes 1 (not happy) — it can never grow unboundedly because for
any number with more than 3 digits, the sum of squared digits is strictly smaller than the
number itself, so the sequence is eventually confined to a small range and must repeat a
value. This "does the sequence terminate or cycle" shape is exactly Floyd's cycle detection
(the same slow/fast pointer technique used for linked list cycles), just applied to a
numeric sequence generated by the digit-square-sum function instead of node->next pointers.
Advance slow by one application of the function and fast by two; if they ever meet before
reaching 1, we're in a cycle and the number is not happy.
*/

#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    bool isHappy(int n) {
        long long slow = n;
        long long fast = sumOfSquaredDigits(n);

        while (fast != 1 && slow != fast) {
            slow = sumOfSquaredDigits(slow);
            fast = sumOfSquaredDigits(sumOfSquaredDigits(fast));
        }
        return fast == 1;
    }

private:
    long long sumOfSquaredDigits(long long x) {
        long long sum = 0;
        while (x > 0) {
            long long d = x % 10;
            sum += d * d;
            x /= 10;
        }
        return sum;
    }
};

int main() {
    Solution sol;

    cout << "Input: n = 19" << endl;
    cout << "Output: " << (sol.isHappy(19) ? "true" : "false") << endl;
    cout << "Expected: true" << endl << endl;

    cout << "Input: n = 2" << endl;
    cout << "Output: " << (sol.isHappy(2) ? "true" : "false") << endl;
    cout << "Expected: false" << endl << endl;

    cout << "Input: n = 1" << endl;
    cout << "Output: " << (sol.isHappy(1) ? "true" : "false") << endl;
    cout << "Expected: true" << endl;

    return 0;
}
